package com.xyd.mybatis.mapper;

import com.xyd.mybatis.model.ApplyLoan;
import com.xyd.mybatis.model.ApplyLoanExample;
import java.util.List;

public interface ApplyLoanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_loan
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    int deleteByPrimaryKey(Long applyLoanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_loan
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    int insert(ApplyLoan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_loan
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    int insertSelective(ApplyLoan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_loan
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    List<ApplyLoan> selectByExample(ApplyLoanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_loan
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    ApplyLoan selectByPrimaryKey(Long applyLoanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_loan
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    int updateByPrimaryKeySelective(ApplyLoan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_loan
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    int updateByPrimaryKey(ApplyLoan record);
}