package com.xyd.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class ApplyLoan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.apply_loan_id
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private Long applyLoanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.loan_number
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String loanNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.merchant_id
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private Long merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.dealer_id
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private Long dealerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.product_no
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String productNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.name
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.id_card
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.mobile
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.bank_card
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String bankCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.bank_name
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.bank_province
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String bankProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.bank_city
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String bankCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.bank_district
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String bankDistrict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.bank_branch
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String bankBranch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.bank_mobile
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String bankMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.store_name
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String storeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.store_province
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String storeProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.store_city
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String storeCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.store_district
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String storeDistrict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.store_address
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String storeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.store_phone
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String storePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.loan_purpose
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String loanPurpose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.loan_amount
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private BigDecimal loanAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.loan_month
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private Integer loanMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.period
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private Integer period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.pre_rate
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private BigDecimal preRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.interest_rate
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private BigDecimal interestRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.interest_rate_unit
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String interestRateUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.repayment_method
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private Byte repaymentMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.approve_amount
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private BigDecimal approveAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.approve_reason
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String approveReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.remark
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.model_result_id
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private Long modelResultId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.esign_deadline
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private Date esignDeadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.esign_time
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private Date esignTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.ob_cn
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String obCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.express_type
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private Byte expressType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.express_com
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String expressCom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.cn
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String cn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.fund_time
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private Date fundTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.status
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.status_desc
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String statusDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.is_reup_fa
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private Byte isReupFa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.is_reup_shou
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private Byte isReupShou;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.is_end
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private Byte isEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.is_deleted
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.create_at
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_loan.update_at
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.apply_loan_id
     *
     * @return the value of apply_loan.apply_loan_id
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public Long getApplyLoanId() {
        return applyLoanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.apply_loan_id
     *
     * @param applyLoanId the value for apply_loan.apply_loan_id
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setApplyLoanId(Long applyLoanId) {
        this.applyLoanId = applyLoanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.loan_number
     *
     * @return the value of apply_loan.loan_number
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getLoanNumber() {
        return loanNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.loan_number
     *
     * @param loanNumber the value for apply_loan.loan_number
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setLoanNumber(String loanNumber) {
        this.loanNumber = loanNumber == null ? null : loanNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.merchant_id
     *
     * @return the value of apply_loan.merchant_id
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.merchant_id
     *
     * @param merchantId the value for apply_loan.merchant_id
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.dealer_id
     *
     * @return the value of apply_loan.dealer_id
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public Long getDealerId() {
        return dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.dealer_id
     *
     * @param dealerId the value for apply_loan.dealer_id
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setDealerId(Long dealerId) {
        this.dealerId = dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.product_no
     *
     * @return the value of apply_loan.product_no
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.product_no
     *
     * @param productNo the value for apply_loan.product_no
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo == null ? null : productNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.name
     *
     * @return the value of apply_loan.name
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.name
     *
     * @param name the value for apply_loan.name
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.id_card
     *
     * @return the value of apply_loan.id_card
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.id_card
     *
     * @param idCard the value for apply_loan.id_card
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.mobile
     *
     * @return the value of apply_loan.mobile
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.mobile
     *
     * @param mobile the value for apply_loan.mobile
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.bank_card
     *
     * @return the value of apply_loan.bank_card
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getBankCard() {
        return bankCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.bank_card
     *
     * @param bankCard the value for apply_loan.bank_card
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setBankCard(String bankCard) {
        this.bankCard = bankCard == null ? null : bankCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.bank_name
     *
     * @return the value of apply_loan.bank_name
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.bank_name
     *
     * @param bankName the value for apply_loan.bank_name
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.bank_province
     *
     * @return the value of apply_loan.bank_province
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getBankProvince() {
        return bankProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.bank_province
     *
     * @param bankProvince the value for apply_loan.bank_province
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setBankProvince(String bankProvince) {
        this.bankProvince = bankProvince == null ? null : bankProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.bank_city
     *
     * @return the value of apply_loan.bank_city
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getBankCity() {
        return bankCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.bank_city
     *
     * @param bankCity the value for apply_loan.bank_city
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setBankCity(String bankCity) {
        this.bankCity = bankCity == null ? null : bankCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.bank_district
     *
     * @return the value of apply_loan.bank_district
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getBankDistrict() {
        return bankDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.bank_district
     *
     * @param bankDistrict the value for apply_loan.bank_district
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setBankDistrict(String bankDistrict) {
        this.bankDistrict = bankDistrict == null ? null : bankDistrict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.bank_branch
     *
     * @return the value of apply_loan.bank_branch
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getBankBranch() {
        return bankBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.bank_branch
     *
     * @param bankBranch the value for apply_loan.bank_branch
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setBankBranch(String bankBranch) {
        this.bankBranch = bankBranch == null ? null : bankBranch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.bank_mobile
     *
     * @return the value of apply_loan.bank_mobile
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getBankMobile() {
        return bankMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.bank_mobile
     *
     * @param bankMobile the value for apply_loan.bank_mobile
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setBankMobile(String bankMobile) {
        this.bankMobile = bankMobile == null ? null : bankMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.store_name
     *
     * @return the value of apply_loan.store_name
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.store_name
     *
     * @param storeName the value for apply_loan.store_name
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName == null ? null : storeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.store_province
     *
     * @return the value of apply_loan.store_province
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getStoreProvince() {
        return storeProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.store_province
     *
     * @param storeProvince the value for apply_loan.store_province
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setStoreProvince(String storeProvince) {
        this.storeProvince = storeProvince == null ? null : storeProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.store_city
     *
     * @return the value of apply_loan.store_city
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getStoreCity() {
        return storeCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.store_city
     *
     * @param storeCity the value for apply_loan.store_city
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setStoreCity(String storeCity) {
        this.storeCity = storeCity == null ? null : storeCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.store_district
     *
     * @return the value of apply_loan.store_district
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getStoreDistrict() {
        return storeDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.store_district
     *
     * @param storeDistrict the value for apply_loan.store_district
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setStoreDistrict(String storeDistrict) {
        this.storeDistrict = storeDistrict == null ? null : storeDistrict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.store_address
     *
     * @return the value of apply_loan.store_address
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getStoreAddress() {
        return storeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.store_address
     *
     * @param storeAddress the value for apply_loan.store_address
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setStoreAddress(String storeAddress) {
        this.storeAddress = storeAddress == null ? null : storeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.store_phone
     *
     * @return the value of apply_loan.store_phone
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getStorePhone() {
        return storePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.store_phone
     *
     * @param storePhone the value for apply_loan.store_phone
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setStorePhone(String storePhone) {
        this.storePhone = storePhone == null ? null : storePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.loan_purpose
     *
     * @return the value of apply_loan.loan_purpose
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getLoanPurpose() {
        return loanPurpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.loan_purpose
     *
     * @param loanPurpose the value for apply_loan.loan_purpose
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setLoanPurpose(String loanPurpose) {
        this.loanPurpose = loanPurpose == null ? null : loanPurpose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.loan_amount
     *
     * @return the value of apply_loan.loan_amount
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public BigDecimal getLoanAmount() {
        return loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.loan_amount
     *
     * @param loanAmount the value for apply_loan.loan_amount
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setLoanAmount(BigDecimal loanAmount) {
        this.loanAmount = loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.loan_month
     *
     * @return the value of apply_loan.loan_month
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public Integer getLoanMonth() {
        return loanMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.loan_month
     *
     * @param loanMonth the value for apply_loan.loan_month
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setLoanMonth(Integer loanMonth) {
        this.loanMonth = loanMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.period
     *
     * @return the value of apply_loan.period
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public Integer getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.period
     *
     * @param period the value for apply_loan.period
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setPeriod(Integer period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.pre_rate
     *
     * @return the value of apply_loan.pre_rate
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public BigDecimal getPreRate() {
        return preRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.pre_rate
     *
     * @param preRate the value for apply_loan.pre_rate
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setPreRate(BigDecimal preRate) {
        this.preRate = preRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.interest_rate
     *
     * @return the value of apply_loan.interest_rate
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public BigDecimal getInterestRate() {
        return interestRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.interest_rate
     *
     * @param interestRate the value for apply_loan.interest_rate
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setInterestRate(BigDecimal interestRate) {
        this.interestRate = interestRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.interest_rate_unit
     *
     * @return the value of apply_loan.interest_rate_unit
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getInterestRateUnit() {
        return interestRateUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.interest_rate_unit
     *
     * @param interestRateUnit the value for apply_loan.interest_rate_unit
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setInterestRateUnit(String interestRateUnit) {
        this.interestRateUnit = interestRateUnit == null ? null : interestRateUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.repayment_method
     *
     * @return the value of apply_loan.repayment_method
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public Byte getRepaymentMethod() {
        return repaymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.repayment_method
     *
     * @param repaymentMethod the value for apply_loan.repayment_method
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setRepaymentMethod(Byte repaymentMethod) {
        this.repaymentMethod = repaymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.approve_amount
     *
     * @return the value of apply_loan.approve_amount
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public BigDecimal getApproveAmount() {
        return approveAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.approve_amount
     *
     * @param approveAmount the value for apply_loan.approve_amount
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setApproveAmount(BigDecimal approveAmount) {
        this.approveAmount = approveAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.approve_reason
     *
     * @return the value of apply_loan.approve_reason
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getApproveReason() {
        return approveReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.approve_reason
     *
     * @param approveReason the value for apply_loan.approve_reason
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setApproveReason(String approveReason) {
        this.approveReason = approveReason == null ? null : approveReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.remark
     *
     * @return the value of apply_loan.remark
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.remark
     *
     * @param remark the value for apply_loan.remark
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.model_result_id
     *
     * @return the value of apply_loan.model_result_id
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public Long getModelResultId() {
        return modelResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.model_result_id
     *
     * @param modelResultId the value for apply_loan.model_result_id
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setModelResultId(Long modelResultId) {
        this.modelResultId = modelResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.esign_deadline
     *
     * @return the value of apply_loan.esign_deadline
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public Date getEsignDeadline() {
        return esignDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.esign_deadline
     *
     * @param esignDeadline the value for apply_loan.esign_deadline
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setEsignDeadline(Date esignDeadline) {
        this.esignDeadline = esignDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.esign_time
     *
     * @return the value of apply_loan.esign_time
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public Date getEsignTime() {
        return esignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.esign_time
     *
     * @param esignTime the value for apply_loan.esign_time
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setEsignTime(Date esignTime) {
        this.esignTime = esignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.ob_cn
     *
     * @return the value of apply_loan.ob_cn
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getObCn() {
        return obCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.ob_cn
     *
     * @param obCn the value for apply_loan.ob_cn
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setObCn(String obCn) {
        this.obCn = obCn == null ? null : obCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.express_type
     *
     * @return the value of apply_loan.express_type
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public Byte getExpressType() {
        return expressType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.express_type
     *
     * @param expressType the value for apply_loan.express_type
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setExpressType(Byte expressType) {
        this.expressType = expressType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.express_com
     *
     * @return the value of apply_loan.express_com
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getExpressCom() {
        return expressCom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.express_com
     *
     * @param expressCom the value for apply_loan.express_com
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setExpressCom(String expressCom) {
        this.expressCom = expressCom == null ? null : expressCom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.cn
     *
     * @return the value of apply_loan.cn
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getCn() {
        return cn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.cn
     *
     * @param cn the value for apply_loan.cn
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setCn(String cn) {
        this.cn = cn == null ? null : cn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.fund_time
     *
     * @return the value of apply_loan.fund_time
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public Date getFundTime() {
        return fundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.fund_time
     *
     * @param fundTime the value for apply_loan.fund_time
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setFundTime(Date fundTime) {
        this.fundTime = fundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.status
     *
     * @return the value of apply_loan.status
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.status
     *
     * @param status the value for apply_loan.status
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.status_desc
     *
     * @return the value of apply_loan.status_desc
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getStatusDesc() {
        return statusDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.status_desc
     *
     * @param statusDesc the value for apply_loan.status_desc
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setStatusDesc(String statusDesc) {
        this.statusDesc = statusDesc == null ? null : statusDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.is_reup_fa
     *
     * @return the value of apply_loan.is_reup_fa
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public Byte getIsReupFa() {
        return isReupFa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.is_reup_fa
     *
     * @param isReupFa the value for apply_loan.is_reup_fa
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setIsReupFa(Byte isReupFa) {
        this.isReupFa = isReupFa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.is_reup_shou
     *
     * @return the value of apply_loan.is_reup_shou
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public Byte getIsReupShou() {
        return isReupShou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.is_reup_shou
     *
     * @param isReupShou the value for apply_loan.is_reup_shou
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setIsReupShou(Byte isReupShou) {
        this.isReupShou = isReupShou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.is_end
     *
     * @return the value of apply_loan.is_end
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public Byte getIsEnd() {
        return isEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.is_end
     *
     * @param isEnd the value for apply_loan.is_end
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setIsEnd(Byte isEnd) {
        this.isEnd = isEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.is_deleted
     *
     * @return the value of apply_loan.is_deleted
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.is_deleted
     *
     * @param isDeleted the value for apply_loan.is_deleted
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.create_at
     *
     * @return the value of apply_loan.create_at
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.create_at
     *
     * @param createAt the value for apply_loan.create_at
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_loan.update_at
     *
     * @return the value of apply_loan.update_at
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_loan.update_at
     *
     * @param updateAt the value for apply_loan.update_at
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}