package com.xyd.mybatis.model;

import java.util.Date;

public class OrderInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_id
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.merchant_id
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private Long merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.dealer_id
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private Long dealerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.id_card
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_no
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_detail
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String orderDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_amount
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private Integer orderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.apply_loan_id
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private Long applyLoanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.loan_number
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private String loanNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.is_valid
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private Byte isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.is_deleted
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.create_at
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.update_at
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_id
     *
     * @return the value of order_info.order_id
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_id
     *
     * @param orderId the value for order_info.order_id
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.merchant_id
     *
     * @return the value of order_info.merchant_id
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.merchant_id
     *
     * @param merchantId the value for order_info.merchant_id
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.dealer_id
     *
     * @return the value of order_info.dealer_id
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public Long getDealerId() {
        return dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.dealer_id
     *
     * @param dealerId the value for order_info.dealer_id
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setDealerId(Long dealerId) {
        this.dealerId = dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.id_card
     *
     * @return the value of order_info.id_card
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.id_card
     *
     * @param idCard the value for order_info.id_card
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_no
     *
     * @return the value of order_info.order_no
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_no
     *
     * @param orderNo the value for order_info.order_no
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_detail
     *
     * @return the value of order_info.order_detail
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getOrderDetail() {
        return orderDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_detail
     *
     * @param orderDetail the value for order_info.order_detail
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setOrderDetail(String orderDetail) {
        this.orderDetail = orderDetail == null ? null : orderDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_amount
     *
     * @return the value of order_info.order_amount
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public Integer getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_amount
     *
     * @param orderAmount the value for order_info.order_amount
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setOrderAmount(Integer orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.apply_loan_id
     *
     * @return the value of order_info.apply_loan_id
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public Long getApplyLoanId() {
        return applyLoanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.apply_loan_id
     *
     * @param applyLoanId the value for order_info.apply_loan_id
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setApplyLoanId(Long applyLoanId) {
        this.applyLoanId = applyLoanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.loan_number
     *
     * @return the value of order_info.loan_number
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public String getLoanNumber() {
        return loanNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.loan_number
     *
     * @param loanNumber the value for order_info.loan_number
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setLoanNumber(String loanNumber) {
        this.loanNumber = loanNumber == null ? null : loanNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.is_valid
     *
     * @return the value of order_info.is_valid
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public Byte getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.is_valid
     *
     * @param isValid the value for order_info.is_valid
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setIsValid(Byte isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.is_deleted
     *
     * @return the value of order_info.is_deleted
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.is_deleted
     *
     * @param isDeleted the value for order_info.is_deleted
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.create_at
     *
     * @return the value of order_info.create_at
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.create_at
     *
     * @param createAt the value for order_info.create_at
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.update_at
     *
     * @return the value of order_info.update_at
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.update_at
     *
     * @param updateAt the value for order_info.update_at
     *
     * @mbggenerated Fri Jun 21 17:22:01 CST 2019
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}